resource_types:

    - name: cron-resource
      type: docker-image
      source:
          repository: cftoolsmiths/cron-resource

resources:

    - name: thrice-daily
      type: cron-resource
      source:
          expression: "30 9,15,21 * * *"
          fire_immediately: true

    - name: cube.evolve.go.repo
      type: git
      source:
          uri: https://github.com/apolloakora/cube.evolve.go.git

jobs:

    - name: go-build
      plan:
          - get: thrice-daily
            trigger: true

          - get: cube.evolve.go.repo

          - task: build-go-project
            config:
                platform: linux/arm64
                image_resource:
                    type: registry-image
                    source:
                        repository: ubuntu
                        tag: 20.04
                run:
                    path: /bin/bash
                    args:
                        - -exc
                        - |
                          apt update
                          dig +short myip.opendns.com @resolver1.opendns.com
                          echo "hello ci/cd world"
                          df -h
